#!/bin/bash

KLIPPERSCREEN_DISPLAY=localhost:0

ret=1
timeout=0
while [ $ret -gt 0 ] && [ $timeout -lt 60 ]
do
    xset -display $KLIPPERSCREEN_DISPLAY -q > /dev/null 2>&1
    ret=$?
    timeout=$( expr $timeout + 1 )
    sleep 1
done
if [ $timeout -lt 60 ]
then
    service xterm start
    exit 0
else
    exit 1
fi
