#!/bin/bash

KLIPPERSCREEN_DISPLAY=127.0.0.1:1
KLIPPERSCREEN_USER=android
KLIPPERSCREEN_CONFIG=/home/$KLIPPERSCREEN_USER/printer_data/config/KlipperScreen.conf
KLIPPERSCREEN_LOG=/home/$KLIPPERSCREEN_USER/printer_data/logs/KlipperScreen.log

ret=1
timeout=0
echo -n "Waiting for x-server to be ready "
while [ $ret -gt 0 ] && [ $timeout -lt 60 ]
do
    xset -display $KLIPPERSCREEN_DISPLAY -q > /dev/null 2>&1
    ret=$?
    timeout=$( expr $timeout + 1 )
    echo -n "."
    sleep 1
done
echo ""
if [ $timeout -lt 60 ]
then
    echo -n "Starting Klipper Screen Xclient Deamon .... "
    DISPLAY=$KLIPPERSCREEN_DISPLAY /home/$KLIPPERSCREEN_USER/.KlipperScreen-env/bin/python /home/$KLIPPERSCREEN_USER/KlipperScreen/screen.py -c $KLIPPERSCREEN_CONFIG -l $KLIPPERSCREEN_LOG
    echo "running"
    exit 0
else
    exit 1
fi
